    opencost:
      exporter:
        defaultClusterId: "test"
        extraEnv:
          RESOLUTION_1D_RETENTION:              15      # Срок хранения данных с дневным разрешением (дни)
          RESOLUTION_1H_RETENTION:              49      # Срок хранения данных с часовым разрешением (часы)
          CLOUD_COST_MONTH_TO_DATE_INTERVAL:    6       # Интервал для расчета затрат за месяц (дни)
          CLOUD_COST_REFRESH_RATE_HOURS:        1       # Частота обновления данных о расходах (часы)
          CLOUD_COST_QUERY_WINDOW_DAYS:         7       # Окно запроса данных о расходах (дни)
          CLOUD_COST_RUN_WINDOW_DAYS:           3       # Окно запуска процессов расчета расходов (дни)
          CLOUD_PROVIDER:                       DEFAULT # Провайдер облака по умолчанию
          KUBECOST_SCRAPE_INTERVAL:             5m     # Интервал сбора метрик Kubecost (минуты)
          PROM_CLUSTER_ID_LABEL:                cluster # Метка кластера для Prometheus
          USE_CUSTOM_PROVIDER:                  true    # Использовать кастомного облачного провайдера
      prometheus:
        external:
          enabled: true
          url: http://vmselect-vmks-victoria-metrics-k8s-stack.vmks.svc.cluster.local:8481/select/0/prometheus
        internal:
          enabled: false
          serviceName: vmselect-vmks-victoria-metrics-k8s-stack
          namespaceName: vmks
          port: 8481
          path: "/select/0/prometheus"
          scheme: http
      customPricing:
        enabled: true
        provider: custom
        costModel:
          CPU: 1.2852                 # ₽ за 1 vCPU-час:contentReference[oaicite:7]{index=7}
          RAM: 0.3348                 # ₽ за 1 ГБ RAM-час:contentReference[oaicite:8]{index=8}
          storage: 0.0179             # ₽ за 1 ГБ SSD-час (12.8628 ₽/720 ч):contentReference[oaicite:9]{index=9}
          LBIngressDataCost: "0.01"
          FirstFiveForwardingRulesCost: "0.0"
          AdditionalForwardingRuleCost: "0.0"
          zoneNetworkEgress: 1.6524   # ₽ за 1 ГБ исходящего трафика:contentReference[oaicite:10]{index=10}
          regionNetworkEgress: 1.6524 # ₽ за 1 ГБ исходящего трафика:contentReference[oaicite:11]{index=11}
          internetNetworkEgress: 1.6524 # ₽ за 1 ГБ исходящего трафика:contentReference[oaicite:12]{index=12}

      ui:
        enabled: true
        modelFqdn: "localhost:9003" # Обход проблемы hairpin NAT в Yandex Cloud K8s: nginx проксирует через localhost вместо ClusterIP
        ingress:
          enabled: true
          ingressClassName: "nginx"
          hosts:
          - host: opencost.apatsev.org.ru
            paths:
            - /
      mcp:
        enabled: true
        ingress:
          enabled: true
          ingressClassName: "nginx"
          hosts:
          - host: mcp-opencost.apatsev.org.ru
            paths:
            - path: /
              pathType: Prefix
      metrics:
        serviceMonitor:
          enabled: true
          namespace: opencost
          interval: 10m
