vmsingle:
  spec:
    podMetadata:
      labels:
        team: metrics # Лейбл для группировки в OpenCost (aggregate=label:team) — стоимость по командам
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - vmsingle.apatsev.org.ru
vmagent:
  spec:
    podMetadata:
      labels:
        team: metrics # Лейбл для группировки в OpenCost (aggregate=label:team) — стоимость по командам
grafana:
  podLabels:
    team: metrics
  ingress:
    ingressClassName: nginx
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - grafana.apatsev.org.ru
vmalert:
  spec:
    podMetadata:
      labels:
        team: metrics # Лейбл для группировки в OpenCost (aggregate=label:team) — стоимость по командам
alertmanager:
  spec:
    podMetadata:
      labels:
        team: metrics
prometheus-node-exporter:
  podLabels:
    team: metrics # Лейбл для группировки в OpenCost (aggregate=label:team) — стоимость по командам
kube-state-metrics:
  podLabels:
    team: metrics # Лейбл для группировки в OpenCost (aggregate=label:team) — стоимость по командам
victoria-metrics-operator:
  podLabels:
    team: metrics # Лейбл для группировки в OpenCost (aggregate=label:team) — стоимость по командам
